'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Menu

    '''<summary>
    '''MenuCategoryRepeaterMobi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MenuCategoryRepeaterMobi As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''MenuCategoryRepeater control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MenuCategoryRepeater As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''rptMenus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptMenus As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''phShoppingCart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents phShoppingCart As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''imgClosedSign control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgClosedSign As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''InProgressModalPopupExtender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents InProgressModalPopupExtender As Global.AjaxControlToolkit.ModalPopupExtender

    '''<summary>
    '''UpdateProgress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdateProgress As Global.System.Web.UI.UpdateProgress

    '''<summary>
    '''PopupDressingLink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PopupDressingLink As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''DressingModalPopupExtender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DressingModalPopupExtender As Global.AjaxControlToolkit.ModalPopupExtender

    '''<summary>
    '''DressingPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DressingPanel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''DLDressing control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DLDressing As Global.System.Web.UI.WebControls.DataList

    '''<summary>
    '''SDSDressing control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SDSDressing As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''ButtonDeleleOkay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonDeleleOkay As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lnkExtraTopping control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkExtraTopping As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''ModalPopupExtenderTopping control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ModalPopupExtenderTopping As Global.AjaxControlToolkit.ModalPopupExtender

    '''<summary>
    '''pnlTopping control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlTopping As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''chkYesTopping control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkYesTopping As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''tbeYesTopping control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbeYesTopping As Global.AjaxControlToolkit.ToggleButtonExtender

    '''<summary>
    '''MutuallyExclusiveCheckBoxExtender1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MutuallyExclusiveCheckBoxExtender1 As Global.AjaxControlToolkit.MutuallyExclusiveCheckBoxExtender

    '''<summary>
    '''chkNoTopping control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkNoTopping As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''tbeNoTopping control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbeNoTopping As Global.AjaxControlToolkit.ToggleButtonExtender

    '''<summary>
    '''MutuallyExclusiveCheckBoxExtender2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MutuallyExclusiveCheckBoxExtender2 As Global.AjaxControlToolkit.MutuallyExclusiveCheckBoxExtender

    '''<summary>
    '''chkLeftTopping control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkLeftTopping As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''tbeLeftTopping control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbeLeftTopping As Global.AjaxControlToolkit.ToggleButtonExtender

    '''<summary>
    '''MutuallyExclusiveCheckBoxExtender3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MutuallyExclusiveCheckBoxExtender3 As Global.AjaxControlToolkit.MutuallyExclusiveCheckBoxExtender

    '''<summary>
    '''chkRightTopping control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkRightTopping As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''tbeRightTopping control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbeRightTopping As Global.AjaxControlToolkit.ToggleButtonExtender

    '''<summary>
    '''MutuallyExclusiveCheckBoxExtender4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MutuallyExclusiveCheckBoxExtender4 As Global.AjaxControlToolkit.MutuallyExclusiveCheckBoxExtender

    '''<summary>
    '''dlToppings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dlToppings As Global.System.Web.UI.WebControls.DataList

    '''<summary>
    '''btnOKTopping control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnOKTopping As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnCancelTopping control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelTopping As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''phOptionPopups control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents phOptionPopups As Global.System.Web.UI.WebControls.PlaceHolder
End Class
