'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class OrderConfirm

    '''<summary>
    '''rptCartItems control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptCartItems As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''ltrBillingName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltrBillingName As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''ltrBillingAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltrBillingAddress As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''ltrBillingPhoneNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltrBillingPhoneNo As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''ltrBillingEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltrBillingEmail As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''billingNamePlaceID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents billingNamePlaceID As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ltrDeliveryName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltrDeliveryName As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''ltrDeliveryAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltrDeliveryAddress As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''ltrDeliveryPhoneNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltrDeliveryPhoneNo As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''ltrDeliveryEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltrDeliveryEmail As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''ltrDeliverTiming control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltrDeliverTiming As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''phSubmitPayment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents phSubmitPayment As Global.System.Web.UI.WebControls.PlaceHolder
End Class
