'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class OrderConfirmation

    '''<summary>
    '''frmSagePay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmSagePay As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''VPSProtocol control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VPSProtocol As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''TxType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxType As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''Vendor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Vendor As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''Crypt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Crypt As Global.System.Web.UI.HtmlControls.HtmlInputHidden
End Class
