'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace [Public].[default]

    Partial Public Class Header

        '''<summary>
        '''pnlOrderTypeAndPostCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlOrderTypeAndPostCode As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''ltrOrderType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ltrOrderType As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''ltrPostcode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ltrPostcode As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''LinkButton4 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LinkButton4 As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''LinkButton1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LinkButton1 As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''lnkLogout control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnkLogout As Global.System.Web.UI.WebControls.LinkButton
    End Class
End Namespace
