'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On
Namespace Admin

    Partial Public Class CustomerOrders

        '''<summary>
        '''smAdmin control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents smAdmin As Global.System.Web.UI.ScriptManager

        '''<summary>
        '''ltrCustomer control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ltrCustomer As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''GoBack control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents GoBack As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''TimePeriodOptions control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TimePeriodOptions As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''upCustomerOrders control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents upCustomerOrders As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''ltrNumberOfOrders control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ltrNumberOfOrders As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''OrdersRepeater control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents OrdersRepeater As Global.System.Web.UI.WebControls.Repeater
    End Class
End Namespace