'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On
Namespace Admin

    Partial Public Class Info

        '''<summary>
        '''ValidationMsg control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ValidationMsg As Global.System.Web.UI.WebControls.ValidationSummary

        '''<summary>
        '''MessageLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents MessageLabel As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''WebsiteName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents WebsiteName As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''WebsiteNameRequired control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents WebsiteNameRequired As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''WebsiteMeta control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents WebsiteMeta As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''SaveChanges control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SaveChanges As Global.System.Web.UI.WebControls.Button
    End Class
End Namespace