'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Admin

    Partial Public Class MenuItem

        '''<summary>
        '''btnNewMenuItem control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnNewMenuItem As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''btnBack control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnBack As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''upMenuItemGrid control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents upMenuItemGrid As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''gvMenuItem control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents gvMenuItem As Global.System.Web.UI.WebControls.GridView

        '''<summary>
        '''upMenuItemView control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents upMenuItemView As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''ltrMenuItemEditorHeaderText control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ltrMenuItemEditorHeaderText As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''hdnMenuItemID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hdnMenuItemID As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''txtCategoryName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCategoryName As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''hdnCategoryID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hdnCategoryID As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''ddlCategories control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlCategories As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''txtMenuItemName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtMenuItemName As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''MenuItemNameRequired control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents MenuItemNameRequired As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''txtItemPosition control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtItemPosition As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtPreparationTime control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtPreparationTime As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''chkActive control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkActive As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''chkBaseSelection control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkBaseSelection As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''radOneSize control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents radOneSize As Global.System.Web.UI.WebControls.RadioButton

        '''<summary>
        '''radMultipleSize control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents radMultipleSize As Global.System.Web.UI.WebControls.RadioButton

        '''<summary>
        '''chkLinkDressingOrTopping control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkLinkDressingOrTopping As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''ddlMenuLink1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlMenuLink1 As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''chkLinkMenu control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkLinkMenu As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''ddlMenuLink2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlMenuLink2 As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''txtDeliveryPrice control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtDeliveryPrice As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtCollectionPrice control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCollectionPrice As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtToppingPrice1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtToppingPrice1 As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtToppingPrice2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtToppingPrice2 As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtToppingPrice3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtToppingPrice3 As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''PromotionText control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PromotionText As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''Remarks control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Remarks As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''btnSaveChanges control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnSaveChanges As Global.System.Web.UI.WebControls.Button
    End Class
End Namespace
