'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class OrderDetails

    '''<summary>
    '''smAdmin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents smAdmin As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''ltrCustomer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltrCustomer As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''GoBack control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GoBack As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''upCustomerOrders control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upCustomerOrders As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''ltrOrderAt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltrOrderAt As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''ltrOrderStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltrOrderStatus As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''ltrOrderType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltrOrderType As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''ltrPaymentStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltrPaymentStatus As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''OrderDetailsRepeater control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OrderDetailsRepeater As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''ltrSubTotal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltrSubTotal As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''ltrOnlineDiscount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltrOnlineDiscount As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''ltrDeliveryCharges control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltrDeliveryCharges As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''ltrTotalAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltrTotalAmount As Global.System.Web.UI.WebControls.Literal
End Class
