'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On
Namespace Admin

    Partial Public Class Postcode

        '''<summary>
        '''btnNewPostcode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnNewPostcode As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''upPostcodeGrid control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents upPostcodeGrid As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''gvPostcode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents gvPostcode As Global.System.Web.UI.WebControls.GridView

        '''<summary>
        '''upPostcodeView control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents upPostcodeView As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''ltrMenuItemEditorHeaderText control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ltrMenuItemEditorHeaderText As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''hdnPostcodeID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hdnPostcodeID As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''phMessage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phMessage As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''ltrMessage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ltrMessage As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''txtPostcode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtPostcode As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''PostCodeRequired control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PostCodeRequired As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''Price control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Price As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''MinimumOrderValue control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents MinimumOrderValue As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''AllowDelivery control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents AllowDelivery As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''btnSaveChanges control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnSaveChanges As Global.System.Web.UI.WebControls.Button
    End Class
End Namespace