'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Admin

    Partial Public Class ReportSettings

        '''<summary>
        '''smReporting control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents smReporting As Global.System.Web.UI.ScriptManager

        '''<summary>
        '''ServicesChargesUpdatePanel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ServicesChargesUpdatePanel As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''ServiceNameTextBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ServiceNameTextBox As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''ServiceChargeTextBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ServiceChargeTextBox As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''chkChargeOnOrder control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkChargeOnOrder As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''ServiceEnabledCheckBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ServiceEnabledCheckBox As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''SaveServiceChargeButton control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SaveServiceChargeButton As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''ServicesChargeDataGrid control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ServicesChargeDataGrid As Global.System.Web.UI.WebControls.DataGrid

        '''<summary>
        '''SaveSettingsButton control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SaveSettingsButton As Global.System.Web.UI.WebControls.Button
    End Class
End Namespace
