'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Admin

    Partial Public Class Settings

        '''<summary>
        '''SettingsScriptManager control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SettingsScriptManager As Global.System.Web.UI.ScriptManager

        '''<summary>
        '''ValidationMsg control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ValidationMsg As Global.System.Web.UI.WebControls.ValidationSummary

        '''<summary>
        '''MessageLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents MessageLabel As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''RestaurantID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RestaurantID As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''ShopName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ShopName As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''ShopNameRequired control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ShopNameRequired As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''ShopNo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ShopNo As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''ShopNoRequired control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ShopNoRequired As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''PostCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PostCode As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''PostCodeRequired control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PostCodeRequired As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''BuildingName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents BuildingName As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''Street control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Street As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''City control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents City As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''Telephone1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Telephone1 As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''Mobile control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Mobile As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''Fax control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Fax As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''Email control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Email As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''DeliveryCharge control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DeliveryCharge As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''DeliveryChargeIsDecimal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DeliveryChargeIsDecimal As Global.System.Web.UI.WebControls.RegularExpressionValidator

        '''<summary>
        '''ServiceCharge control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ServiceCharge As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''ServiceChargeIsDecimal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ServiceChargeIsDecimal As Global.System.Web.UI.WebControls.RegularExpressionValidator

        '''<summary>
        '''EnableCashPayments control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents EnableCashPayments As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''EnableNochex control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents EnableNochex As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''OnlineDiscountTextBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents OnlineDiscountTextBox As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''OnlineDiscountMaskedEditExtender control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents OnlineDiscountMaskedEditExtender As Global.AjaxControlToolkit.MaskedEditExtender

        '''<summary>
        '''WebsiteStatus control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents WebsiteStatus As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''SaveRestautanSettings control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SaveRestautanSettings As Global.System.Web.UI.WebControls.Button
    End Class
End Namespace
