'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On
Namespace Admin

    Partial Public Class StaticPages

        '''<summary>
        '''ContactUsViewLink control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ContactUsViewLink As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''AboutUsViewLink control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents AboutUsViewLink As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''StaticPagesTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents StaticPagesTitle As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''ErrorMessages control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ErrorMessages As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''StaticPagesMultiView control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents StaticPagesMultiView As Global.System.Web.UI.WebControls.MultiView

        '''<summary>
        '''ContactUsView control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ContactUsView As Global.System.Web.UI.WebControls.View

        '''<summary>
        '''ContactUsID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ContactUsID As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''MapImage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents MapImage As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''MapImageFileUpload control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents MapImageFileUpload As Global.System.Web.UI.WebControls.FileUpload

        '''<summary>
        '''MapImageFileUploadButton control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents MapImageFileUploadButton As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''ContactInfo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ContactInfo As Global.CKEditor.NET.CKEditorControl

        '''<summary>
        '''AboutUsView control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents AboutUsView As Global.System.Web.UI.WebControls.View

        '''<summary>
        '''AboutUsID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents AboutUsID As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''AboutUsEditor control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents AboutUsEditor As Global.CKEditor.NET.CKEditorControl

        '''<summary>
        '''SaveChanges control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SaveChanges As Global.System.Web.UI.WebControls.Button
    End Class
End Namespace