'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Admin

    Partial Public Class SubMenuItem

        '''<summary>
        '''btnNewMenuItem control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnNewMenuItem As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''btnBack control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnBack As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''upSubMenuItemGrid control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents upSubMenuItemGrid As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''gvSubMenuItem control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents gvSubMenuItem As Global.System.Web.UI.WebControls.GridView

        '''<summary>
        '''upMenuItemView control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents upMenuItemView As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''ltrMenuItemEditorHeaderText control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ltrMenuItemEditorHeaderText As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''hdnSubMenuItemId control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hdnSubMenuItemId As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''phMessage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phMessage As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''ltrMessage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ltrMessage As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''txtMenuItem control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtMenuItem As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''hdnMenuItemId control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hdnMenuItemId As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''txtSubMenuItemName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtSubMenuItemName As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''MenuItemNameRequired control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents MenuItemNameRequired As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''txtItemPosition control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtItemPosition As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtPreparationTime control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtPreparationTime As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''chkActive control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkActive As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''txtDeliveryPrice control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtDeliveryPrice As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtCollectionPrice control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCollectionPrice As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtToppingPrice1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtToppingPrice1 As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtToppingPrice2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtToppingPrice2 As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtToppingPrice3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtToppingPrice3 As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''btnSaveChanges control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnSaveChanges As Global.System.Web.UI.WebControls.Button
    End Class
End Namespace
