'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Admin

    Partial Public Class Themes

        '''<summary>
        '''ThemesScriptManager control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ThemesScriptManager As Global.System.Web.UI.ScriptManager

        '''<summary>
        '''ErrorMessages control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ErrorMessages As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''ShowLogoAndSloganView control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ShowLogoAndSloganView As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''ShowNavigationImagesView control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ShowNavigationImagesView As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''ShowHeaderView control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ShowHeaderView As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''ShowFooterView control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ShowFooterView As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''ShowHomePageView control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ShowHomePageView As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''ShowMenuCategory control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ShowMenuCategory As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''ThemesMultiView control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ThemesMultiView As Global.System.Web.UI.WebControls.MultiView

        '''<summary>
        '''LogoAndSloganView control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LogoAndSloganView As Global.System.Web.UI.WebControls.View

        '''<summary>
        '''Slogan control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Slogan As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''LogoImageWidth control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LogoImageWidth As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''LogoImageHeight control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LogoImageHeight As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''Logo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Logo As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''LogoFileUpload control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LogoFileUpload As Global.System.Web.UI.WebControls.FileUpload

        '''<summary>
        '''LogoFileUploadButton control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LogoFileUploadButton As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''NavigationImagesView control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents NavigationImagesView As Global.System.Web.UI.WebControls.View

        '''<summary>
        '''NavigationImageWitdh control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents NavigationImageWitdh As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''NavigationImageHeight control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents NavigationImageHeight As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''NavigationImage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents NavigationImage As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''NavigationImageFileUpload control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents NavigationImageFileUpload As Global.System.Web.UI.WebControls.FileUpload

        '''<summary>
        '''NavigationImageFileUploadButton control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents NavigationImageFileUploadButton As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''NavigationHoverImageWidth control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents NavigationHoverImageWidth As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''NavigationHoverImageHeight control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents NavigationHoverImageHeight As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''NavigationHoverImage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents NavigationHoverImage As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''NavigationHoverImageFileUpload control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents NavigationHoverImageFileUpload As Global.System.Web.UI.WebControls.FileUpload

        '''<summary>
        '''NavigationHoverImageFileUploadButton control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents NavigationHoverImageFileUploadButton As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''HeaderView control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents HeaderView As Global.System.Web.UI.WebControls.View

        '''<summary>
        '''HeaderBgImageWidth control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents HeaderBgImageWidth As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''HeaderBgImageHeight control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents HeaderBgImageHeight As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''HeaderBgImage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents HeaderBgImage As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''HeaderBgImageFileUpload control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents HeaderBgImageFileUpload As Global.System.Web.UI.WebControls.FileUpload

        '''<summary>
        '''HeaderBgImageFileUploadButton control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents HeaderBgImageFileUploadButton As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''FooterView control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents FooterView As Global.System.Web.UI.WebControls.View

        '''<summary>
        '''FooterbgImageWidth control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents FooterbgImageWidth As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''FooterbgImageHeight control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents FooterbgImageHeight As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''FooterbgImage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents FooterbgImage As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''FooterbgImageFileUpload control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents FooterbgImageFileUpload As Global.System.Web.UI.WebControls.FileUpload

        '''<summary>
        '''FooterbgImageFileUploadButton control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents FooterbgImageFileUploadButton As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''HomePageView control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents HomePageView As Global.System.Web.UI.WebControls.View

        '''<summary>
        '''HomePageBgImageWidth control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents HomePageBgImageWidth As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''HomePageBgImageHeight control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents HomePageBgImageHeight As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''HomePageBgImage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents HomePageBgImage As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''HomePageBgImageFileUpload control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents HomePageBgImageFileUpload As Global.System.Web.UI.WebControls.FileUpload

        '''<summary>
        '''HomePageBgImageFileUploadButton control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents HomePageBgImageFileUploadButton As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''MenuCategoryView control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents MenuCategoryView As Global.System.Web.UI.WebControls.View

        '''<summary>
        '''MenuCategoryWidth control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents MenuCategoryWidth As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''MenuCategoryHeight control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents MenuCategoryHeight As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''EditOrderImage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents EditOrderImage As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''EditOrderImageFileUpload control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents EditOrderImageFileUpload As Global.System.Web.UI.WebControls.FileUpload

        '''<summary>
        '''EditOrderImageUploadButton control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents EditOrderImageUploadButton As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''ConfirmOrderImage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ConfirmOrderImage As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''ConfirmOrderFileUpload control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ConfirmOrderFileUpload As Global.System.Web.UI.WebControls.FileUpload

        '''<summary>
        '''ConfirmOrderUploadButton control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ConfirmOrderUploadButton As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''CheckOutImage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CheckOutImage As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''CheckOutFileUpload control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CheckOutFileUpload As Global.System.Web.UI.WebControls.FileUpload

        '''<summary>
        '''CheckOutButton control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CheckOutButton As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''AddToCartImage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents AddToCartImage As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''AddToCartFileUpload control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents AddToCartFileUpload As Global.System.Web.UI.WebControls.FileUpload

        '''<summary>
        '''AddToCartButton control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents AddToCartButton As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''BaseColorSampleLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents BaseColorSampleLabel As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''BaseColorTextBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents BaseColorTextBox As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''BaseColorPopupButton control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents BaseColorPopupButton As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''BaseColorPickerExtender control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents BaseColorPickerExtender As Global.AjaxControlToolkit.ColorPickerExtender

        '''<summary>
        '''BackColorSampleLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents BackColorSampleLabel As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''BackColorTextBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents BackColorTextBox As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''BackColorPopupButton control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents BackColorPopupButton As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''BackColorPickerExtender control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents BackColorPickerExtender As Global.AjaxControlToolkit.ColorPickerExtender

        '''<summary>
        '''SaveThemesSettings control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SaveThemesSettings As Global.System.Web.UI.WebControls.Button
    End Class
End Namespace
