'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Admin

    Partial Public Class TodayOrders

        '''<summary>
        '''StartDateOnTextBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents StartDateOnTextBox As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''EndDateOnTextBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents EndDateOnTextBox As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''SearchButton control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SearchButton As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''ltrNumberOfOrders control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ltrNumberOfOrders As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''OrderDataGrid control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents OrderDataGrid As Global.System.Web.UI.WebControls.DataGrid
    End Class
End Namespace
