'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On
Namespace Admin

    Partial Public Class UserDetails

        '''<summary>
        '''MessageBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents MessageBox As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''Messages control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Messages As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''UserNameTextBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UserNameTextBox As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''EmailTextBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents EmailTextBox As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''IsActivedTextBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents IsActivedTextBox As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''UserRoleTextBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UserRoleTextBox As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''ChangePasswordButton control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ChangePasswordButton As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''BlockAndUnBlockButton control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents BlockAndUnBlockButton As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''CancelButton control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CancelButton As Global.System.Web.UI.WebControls.Button
    End Class
End Namespace