'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Ajax

    Partial Public Class SmallShoppingCartWithoutDeals

        '''<summary>
        '''lblShopCartHeader control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblShopCartHeader As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''mvShoppingCart control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents mvShoppingCart As Global.System.Web.UI.WebControls.MultiView

        '''<summary>
        '''vEmptyCart control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents vEmptyCart As Global.System.Web.UI.WebControls.View

        '''<summary>
        '''vNonEmptyCart control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents vNonEmptyCart As Global.System.Web.UI.WebControls.View

        '''<summary>
        '''phMessageBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phMessageBox As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''rptCartItems control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rptCartItems As Global.System.Web.UI.WebControls.Repeater

        '''<summary>
        '''phCheckOutButton control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phCheckOutButton As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''TotalPrice control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TotalPrice As Global.System.Web.UI.WebControls.Literal
    End Class
End Namespace
